[build]
  base    = "docs/"
  publish = "docs/public/"
  command = "gatsby build --prefix-paths && mkdir -p docs/android && mv public/* docs/android && mv docs public/"
[build.environment]
  NPM_VERSION = "6"
